services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
    ports:
      - '3306:3306'
    volumes:
      - ../data:/var/lib/mysql

  backend:
    container_name: backend
    build: .
    ports:
      - 8080:80
    volumes:
      - ../:/var/www/backend
    depends_on:
      - database